version: '3'
services:
    nodejsmailapp:
        build:
            context: ./node-mail-activation
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        container_name: nodejsmailapp
        restart: on-failure
        volumes:
            - ./node-mail-activation:/usr/src/app/node-mail-activation
            - /usr/src/app/node-mail-activation/node_modules
        depends_on:
            - nodejsuserapp
    nodejsuserapp:
        build:
            context: ./node-mysql-registration
            dockerfile: Dockerfile
        ports:
            - "4000:4000"
        container_name: nodejsuserapp
        restart: on-failure
        volumes:
            - ./node-mysql-registration:/usr/src/app/node-mysql-registration
            - /usr/src/app/node-mysql-registration/node_modules
        depends_on:
            - mysqlcodegym
    nodejsloadbalancer:
        build:
            context: ./node-loadbalancer
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        container_name: nodejsloadbalancer
        restart: on-failure
        volumes:
            - ./node-loadbalancer:/usr/src/app/node-loadbalancer
            - /usr/src/app/node-loadbalancer/node_modules
        depends_on:
            - nodejsmailapp
    angularcodegym:
        build:
            context: ./CodeChallenge
            dockerfile: Dockerfile
        ports:
            - "4210:4210"
        container_name: codegym-ui
        volumes:
            - ./CodeChallenge:/usr/src/app/CodeChallenge
            - /usr/src/app/CodeChallenge/node_modules
        depends_on:
            - nodejsmailapp
            - nodejsuserapp
            - nodejsloadbalancer
    mysqlcodegym:
        container_name: mysqlcodegym
        image: mysql
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: gymtimedb
            MYSQL_ROOT_PASSWORD: mysql1234
            MYSQL_ROOT_HOST: '%'
